AWSTemplateFormatVersion: '2010-09-09'
Metadata: 
  License: Apache-2.0
Parameters:
  FullWebsiteDomainName:
    Type: String
    Description: e.g. pgaimpact.org or impact.sandboxpga.org. DO NOT add www.
  CreateWWW: 
    Type: String
    Description: e.g. www.pgaimpact.org. Do not use if main website uses a subdomain. Wildcard SSL cert won't be valid for www.impact.sandboxpga.org
    AllowedValues: [true, false]
    Default: true
  Route53HostedZoneId:
    Type: "AWS::Route53::HostedZone::Id"
    Description: Hosted Zone Id of the domain
  AcmCertificateArn:
    Type: String
    Description: The ARN of an ACM SSL certificate. e.g arn:aws:acm:us-east-1:XXXXX:certificate/aaaa-bbbb-ccc-ddd-eeee
    AllowedPattern: "arn:aws:acm:.*"
  CloudfrontDefaultTTL:
    Type: Number
    Description: The default time in seconds that objects stay in CloudFront cache.
    Default: 86400
      
Conditions: 
  CreateWWWRedirect: !Equals [ !Ref CreateWWW, true ]

Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - 
        Label: 
          default: "Domain"
        Parameters: 
          - FullWebsiteDomainName
          - CreateWWW
          - Route53HostedZoneId
    ParameterLabels:
      FullWebsiteDomainName: 
        default: "Full Domain Name"
      CreateWWW: 
        default: "Auto-create www Redirect"
      Route53HostedZoneId: 
        default: "Hosted Zone ID"
      AcmCertificateArn: 
        default: "ACM SSL Certificate ARN"
      CloudfrontDefaultTTL: 
        default: "Default Cache TTL"
          
Mappings:
  RegionMap:
    us-east-1:
      Suffix: .s3-website-us-east-1.amazonaws.com
    us-west-1:
      Suffix: .s3-website-us-west-1.amazonaws.com
    us-west-2:
      Suffix: .s3-website-us-west-2.amazonaws.com
    eu-west-1:
      Suffix: .s3-website-eu-west-1.amazonaws.com
    ap-northeast-1:
      Suffix: .s3-website-ap-northeast-1.amazonaws.com
    ap-northeast-2:
      Suffix: .s3-website-ap-northeast-2.amazonaws.com
    ap-southeast-1:
      Suffix: .s3-website-ap-southeast-1.amazonaws.com
    ap-southeast-2:
      Suffix: .s3-website-ap-southeast-2.amazonaws.com
    ap-south-1:
      Suffix: .s3-website-ap-south-1.amazonaws.com
    us-east-2:
      Suffix: .s3-website-us-east-2.amazonaws.com
    sa-east-1:
      Suffix: .s3-website-sa-east-1.amazonaws.com
    cn-north-1:
      Suffix: .s3-website.cn-north-1.amazonaws.com.cn
    eu-central-1:
      Suffix: .s3-website.eu-central-1.amazonaws.com

Resources:
  S3BucketForWebsite:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref FullWebsiteDomainName
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html
  
  S3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref 'S3BucketForWebsite'
        PolicyDocument:
          Statement:
          - Sid: PublicRead
            Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Join ['', ['arn:aws:s3:::', !Ref 'S3BucketForWebsite', '/*']]
  
  S3BucketForRedirect:
    Type: AWS::S3::Bucket
    Condition: CreateWWWRedirect
    Properties:
      BucketName: !Join ['.', ['www', !Ref FullWebsiteDomainName]]
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: !Ref FullWebsiteDomainName # Redirect to non-www version
          Protocol: https
  
  CfDistroForWebsite:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: 'true'
        Comment: static website
        Aliases:
          - !Ref FullWebsiteDomainName
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          DefaultTTL: !Ref CloudfrontDefaultTTL
          Compress: 'true'
          ForwardedValues:
            QueryString: 'true'
        HttpVersion: http2
        IPV6Enabled: 'true'
        ViewerCertificate:
          AcmCertificateArn: !Ref AcmCertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1_2016
        Origins:
          - Id: S3Origin
            DomainName: !Join ['', [!Ref 'S3BucketForWebsite', !FindInMap [RegionMap, !Ref 'AWS::Region', Suffix]]]
            CustomOriginConfig:
              HTTPPort: '80'
              HTTPSPort: '443'
              OriginProtocolPolicy: http-only
          
  CfDistroForRedirect:
    Type: AWS::CloudFront::Distribution
    Condition: CreateWWWRedirect
    Properties:
      DistributionConfig:
        Enabled: 'true'
        Comment: www-redirect
        Aliases:
          - !Join ['.', ['www', !Ref FullWebsiteDomainName]]
        DefaultCacheBehavior:
          TargetOriginId: S3RedirectOrigin
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            QueryString: 'true'
        HttpVersion: http2
        IPV6Enabled: 'true'
        ViewerCertificate:
          AcmCertificateArn: !Ref AcmCertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1_2016
        Origins:
          - Id: S3RedirectOrigin
            DomainName: !Join ['', [!Ref 'S3BucketForRedirect', !FindInMap [RegionMap, !Ref 'AWS::Region', Suffix]]]
            CustomOriginConfig:
              HTTPPort: '80'
              HTTPSPort: '443'
              OriginProtocolPolicy: http-only  
              
  DNSNameForWebsite:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref Route53HostedZoneId
      RecordSets:
      - 
        Name: !Ref FullWebsiteDomainName
        Type: A # IPv4 Record
        AliasTarget:
          HostedZoneId: 'Z2FDTNDATAQYW2' # Value for ALL Cloudfront targets
          DNSName: !GetAtt CfDistroForWebsite.DomainName
      - 
        Name: !Ref FullWebsiteDomainName
        Type: AAAA # IPv6 Record
        AliasTarget:
          HostedZoneId: 'Z2FDTNDATAQYW2'
          DNSName: !GetAtt CfDistroForWebsite.DomainName

  DNSNameForRedirect:
    Type: AWS::Route53::RecordSetGroup
    Condition: CreateWWWRedirect
    Properties:
      HostedZoneId: !Ref Route53HostedZoneId
      RecordSets:
      - 
        Name: !Join ['.', ['www', !Ref FullWebsiteDomainName]]
        Type: A # IPv4 Record
        AliasTarget:
          HostedZoneId: 'Z2FDTNDATAQYW2'
          DNSName: !GetAtt CfDistroForRedirect.DomainName
      - 
        Name: !Join ['.', ['www', !Ref FullWebsiteDomainName]]
        Type: AAAA # IPv6 Record
        AliasTarget:
          HostedZoneId: 'Z2FDTNDATAQYW2'
          DNSName: !GetAtt CfDistroForRedirect.DomainName
        
Outputs:
  WebsiteURL:
    Value: !Join ['', ['https://', !Ref FullWebsiteDomainName]]
    Description: The URL of the newly created website
  BucketName:
    Value: !Ref 'S3BucketForWebsite'
    Description: Name of S3 bucket to hold website content