version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7-stretch

    steps:
      - checkout

      - run:
          name: install awscli
          command: sudo pip install --upgrade awscli

      - run:
          name: update aws profiles
          command: mkdir ~/.aws && cp -f .circleci/.aws/config ~/.aws/config

      - deploy:
          name: Deploy to S3
          command: aws s3 sync . s3://pgaimpact.org/
                   --profile circleci-prod
                   --exclude ".git/*" --exclude ".circleci/*" --exclude ".cloudformation/*" --exclude "README.md"
                   --delete
